#!/usr/bin/env python
# -*- coding: utf-8 -*-
import cmd
from websocket import create_connection
iphost = "127.0.0.1"
class Cli(cmd.Cmd):
    def __init__(self):
        cmd.Cmd.__init__(self)
        self.prompt = "> "
        self.intro  = "Добро пожаловать\nДля справки наберите 'help'"
        self.doc_header ="Доступные команды (для справки по конкретной команде наберите 'help _команда_')"

    def do_host(self, args):
        """ip address host"""
	if len(args) == 0:
		print iphost
    def do_echo(self, args):
	"""echo [М] [N] выполняем М запросов в серии, N серий"""
	print iphost
	if len(args) == 0:
		a="1"
	else:	a=args.split(" ")
	l=len(a)
	if l > 2: print "Аргументов должно быть не больше двух"
	if l >= 2:
		n = int(a[1])
        	m = int(a[0])
	if l == 1:
		n = 1
		m = int(a[0])
	if l == 0:
		n = 1
		m = 1
	j = 0
	while j < n:
		ws = create_connection("ws://"+iphost+"/echo")
		print "CONNECT to "+iphost+" ##############################"
		i=0
		while i < m:
			print "-------------------------------------"
			print "Sending 'Hello, websocket'..."
			ws.send("Hello, websocket")
			print "Sent"
			print "Receiving..."
			result = ws.recv()
			print "Received '%s'" % result
			i=i+1
		ws.close()
		j=j+1

    def default(self, line):
        print "Несуществующая команда"

if __name__ == "__main__":
    cli = Cli()
    try:
        cli.cmdloop()
    except KeyboardInterrupt:
        print "завершение сеанса..."
